# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ia_analysis_pb2 as ia__analysis__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ia_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IaAnalysisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/castor.ia.IaAnalysisService/StartSession',
                request_serializer=ia__analysis__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=ia__analysis__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.AnalysisStream = channel.stream_stream(
                '/castor.ia.IaAnalysisService/AnalysisStream',
                request_serializer=ia__analysis__pb2.ClientMessage.SerializeToString,
                response_deserializer=ia__analysis__pb2.ServerEvent.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/castor.ia.IaAnalysisService/EndSession',
                request_serializer=ia__analysis__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=ia__analysis__pb2.EndSessionResponse.FromString,
                _registered_method=True)


class IaAnalysisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalysisStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IaAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=ia__analysis__pb2.StartSessionRequest.FromString,
                    response_serializer=ia__analysis__pb2.StartSessionResponse.SerializeToString,
            ),
            'AnalysisStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalysisStream,
                    request_deserializer=ia__analysis__pb2.ClientMessage.FromString,
                    response_serializer=ia__analysis__pb2.ServerEvent.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=ia__analysis__pb2.EndSessionRequest.FromString,
                    response_serializer=ia__analysis__pb2.EndSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'castor.ia.IaAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('castor.ia.IaAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IaAnalysisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/castor.ia.IaAnalysisService/StartSession',
            ia__analysis__pb2.StartSessionRequest.SerializeToString,
            ia__analysis__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalysisStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/castor.ia.IaAnalysisService/AnalysisStream',
            ia__analysis__pb2.ClientMessage.SerializeToString,
            ia__analysis__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/castor.ia.IaAnalysisService/EndSession',
            ia__analysis__pb2.EndSessionRequest.SerializeToString,
            ia__analysis__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
